services:
  cart_service:
    build:
      context: ./cart_service
    expose:
      - "9000"
    volumes:
      - ./cart_service:/var/www
    networks:
      - ecommerce_network

  customer_service:
    build:
      context: ./customer_service
    expose:
      - "9000"
    volumes:
      - ./customer_service:/var/www
    networks:
      - ecommerce_network

  product_service:
    build:
      context: ./product_service
    expose:
      - "9000"
    volumes:
      - ./product_service:/var/www
    networks:
      - ecommerce_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Porta de entrada para o Nginx
    depends_on:
      - cart_service
      - customer_service
      - product_service
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
