services:
  cart_service:
    build:
      context: ./cart_service
    expose:
      - "9000"
    volumes:
      - ./cart_service:/var/www
    networks:
      - ecommerce_network
    environment:
      - DATABASE_HOST=cart_db
      - DATABASE_NAME=cart_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword

  customer_service:
    build:
      context: ./customer_service
    expose:
      - "9000"
    volumes:
      - ./customer_service:/var/www
    networks:
      - ecommerce_network
    environment:
      - DATABASE_HOST=customer_db
      - DATABASE_NAME=customer_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword

  product_service:
    build:
      context: ./product_service
    expose:
      - "9000"
    volumes:
      - ./product_service:/var/www
    networks:
      - ecommerce_network
    environment:
      - DATABASE_HOST=product_db
      - DATABASE_NAME=product_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword

  cart_db:
    image: mysql:8.0
    volumes:
      - cart_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cart_db
      - MYSQL_ROOT_PASSWORD=yourpassword
    networks:
      - ecommerce_network

  customer_db:
    image: mysql:8.0
    volumes:
      - customer_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=customer_db
      - MYSQL_ROOT_PASSWORD=yourpassword
    networks:
      - ecommerce_network

  product_db:
    image: mysql:8.0
    volumes:
      - product_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=product_db
      - MYSQL_ROOT_PASSWORD=yourpassword
    networks:
      - ecommerce_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - cart_service
      - customer_service
      - product_service
    networks:
      - ecommerce_network

volumes:
  cart_db_data:
  customer_db_data:
  product_db_data:

networks:
  ecommerce_network:
